(provisioning_template) add multi-disk to disk_enc_clevis_tang.erb
Add support for multiple luks encrypted drives.

diff --git a/provisioning_templates/snippet/disk_enc_clevis_tang.erb b/provisioning_templates/snippet/disk_enc_clevis_tang.erb
--- a/provisioning_templates/snippet/disk_enc_clevis_tang.erb
+++ b/provisioning_templates/snippet/disk_enc_clevis_tang.erb
@@ -26,57 +26,31 @@ description: |
 
 <% if (@host.operatingsystem.family == 'Redhat' || @host.operatingsystem.name == 'Ubuntu') && tang_server_list.present? -%>
 
-cat > /tmp/rootdir-luks-device.sh << "EOF"
-#!/bin/sh
-#
-# Author Jan Löser <loeser@atix.de>
-# Published under the GNU Public Licence 3
-#
-# This scripts tries to find the 1st LUKS device for / (root directory).
-#
-set -o pipefail
+mapfile -t luksdevs < <(lsblk --fs -r | grep crypto_LUKS | awk '{ print $1 }' | xargs -I DEV echo /dev/DEV)
 
-rootdev=$(df / --output=source | tail -n1)
-targetdev=$(readlink -f $rootdev)
-slavedev=$targetdev
-
-while : ; do
-    /sbin/cryptsetup luksDump $slavedev &>/dev/null && echo $slavedev && exit 0
-    set -e
-    slave=$(find /sys/class/block/$(basename $slavedev)/slaves -type l | head -n1)
-    slavedev=$(find /dev -name "$(basename $slave)" | head -n1)
-    set +e
-done
-
-exit 1
-EOF
-
-# needs bash here because Ubuntu's sh (dash) doesn't support `-o pipefail` option
-luksdev=$(bash /tmp/rootdir-luks-device.sh)
-
-if [[ -n "$luksdev" ]]; then
-  echo "LUKS device found for '/': $luksdev"
-
-<% if @host.operatingsystem.family == 'Redhat' %>
+if [[ ${#luksdevs[@]} -gt 0 ]]; then
+<% if @host.operatingsystem.family == 'Redhat' -%>
   if [ -f /usr/bin/dnf ]; then
     dnf -y install <%= packages_redhat %>
   else
     yum -t -y install <%= packages_redhat %>
   fi
-<% elsif @host.operatingsystem.name == 'Ubuntu' %>
+<% elsif @host.operatingsystem.name == 'Ubuntu' -%>
   apt -y install clevis clevis-luks clevis-initramfs clevis-systemd
-<% end %>
-
-<% for tang_server in tang_server_list -%>
-  echo '<%= passphrase %>' | clevis luks bind -y -k - -d $luksdev tang '{"url": "<%= tang_server %>"}'
-  if [[ $? -ne 0 ]]; then
-    echo "---"
-    echo "There was an error during Clevis LUKS bind of '$luksdev' to Tang server '<%= tang_server %>'."
-    echo "System halted."
-    sleep infinity
-  fi
 <% end -%>
-  echo '<%= passphrase %>' | cryptsetup luksRemoveKey $luksdev
+
+  for dev in "${luksdevs[@]}"; do
+<% for tang_server in tang_server_list -%>
+    if ! echo '<%= passphrase %>' | clevis luks bind -y -k - -d "$dev" tang '{"url": "<%= tang_server %>"}'; then
+      echo "---"
+      echo "There was an error during Clevis LUKS bind of '$dev' to Tang server '<%= tang_server %>'."
+      echo "System halted."
+      sleep infinity
+    fi
+<% end -%>
+    echo '<%= passphrase %>' | cryptsetup luksRemoveKey "$dev"
+  done
+
   systemctl enable clevis-luks-askpass.path
   systemctl enable remote-cryptsetup.target
 
@@ -85,7 +59,6 @@ if [[ -n "$luksdev" ]]; then
 <% elsif @host.operatingsystem.name == 'Ubuntu' -%>
   update-initramfs -u -k 'all'
 <% end -%>
-
 else
   echo "No LUKS device found!"
 fi
